<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl=" href="employee.xsl"?>
<!DOCTYPE Listname [
<!ELEMENT Listname (employee*)>
<!ELEMENT employee (name, position, tel, email, date)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT date (#PCDATA)>
]>

<Listname>
    <employee>
        <name>Raeliana McMillan</name>
        <position>Store Manager</position>
        <tel>+1-555-678-1234</tel>
        <email>Raeliana@bookstore.com</email>
        <date>2018/05/15</date>
    </employee>
    <employee>
        <name>Florentia Lombardi</name>
        <position>Assistant Manager</position>
        <tel>+1-555-789-2345</tel>
        <email>Florentia@bookstore.com</email>
        <date>2019/07/22</date>
    </employee>
    <employee>
        <name>Aria Roscente</name>
        <position>Cashier</position>
        <tel>+1-555-890-3456</tel>
        <email>Aria@bookstore.com</email>
        <date>2020/03/10</date>
    </employee>
    <employee>
        <name>Calliope Rustichel</name>
        <position>Sales Associate</position>
        <tel>+1-555-901-4567</tel>
        <email>Calliope @bookstore.com</email>
        <date>2021/09/01</date>
    </employee>
    <employee>
        <name>Elise de Clorance</name>
        <position>Inventory Specialist</position>
        <tel>+1-555-012-5678</tel>
        <email>Elise.de@bookstore.com</email>
        <date>2022/11/05</date>
    </employee>
</Listname>