<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl=" href="product.xsl"?>
<!DOCTYPE Bookshop [
<!ELEMENT Bookshop (product*)>
<!ELEMENT product (id, name, details, price, quantity)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT details (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
]>

<Bookshop>
    <product>
        <id>BK001</id>
        <name>The Girl from the Other Side</name>
        <details>ชิวาและอาจารย์ต้องย้ายหนีจากบ้านเพราะกำลังถูกทหารจากอาณาจักรด้านในตามล่า
        พวกเขาจำเป็นต้องหาสถานที่ปลอดภับเพื่อซ่อนตัว ทั้งสองได้ออกเดินทางไปยังสถานที่แห่งใหม่
        ทว่าเเม้จะหนีมาห่างไกลแล้วแต่ก็ยังคงไม่อาจหลีกหนีจากชะตากรรมได้พ้น การไล่ล่าของทหารต้องคำสาป
        แผนการของอาณาจักรด้านใน เเละอดีตอันคลุมเครือของอาจารย์กำลังจะถูกเปิดเผย
        </details>
        <price>฿156</price>
        <quantity>190 เล่ม</quantity>
    </product>
    <product>
        <id>BK002</id>
        <name>Who made me a princess</name>
        <details>พอลืมตาขึ้นมาอีกที ฉันก็กลายเป็นเจ้าหญิงไปเสียแล้วการได้เกิดมาคาบช้อนเงินช้อนทองมันก็ดีอยู่หรอกแต่ทำไมต้องเป็น 'อาทาเนเซีย' เจ้าหญิงต๊อกต๋อยที่ต้อง
        ตายด้วยน้ำมือของพ่อแท้ๆอย่าง'โคลด์'จักรพรรดิจอมเย็นชาผู้ไร้หัวใจคนนั้นด้วยล่ะ!ฉะนั้นถ้ายังอยากมีชีวิตรอดต่อไปละก็ห้ามทำเหมือนมีตัวตนในสายตาของหมอนั่นเด็ดขาด!
        ทว่า...อยู่มาวันหนึ่ง ฉันก็ไปบังเอิญเจอโคลด์เข้าเพื่อเอาชีวิตรอด ฉันจะต้องหาวิธีประจบเอาใจและกลายเป็นลูกรักของเขาให้จงได้
        </details>
        <price>฿414</price>
        <quantity>175 เล่ม</quantity>
    </product>
    <product>
        <id>BK003</id>
        <name>BRUTAL คำสารภาพของตำรวจฆาตกร</name>
        <details>ให้คนชั่วอาบความสิ้นหวัง
            ความตายอันเลวร้ายสุดแก่คนโฉดชั่ว
            ที่ไม่อาจพิพากษาด้วยกฏหมาย
            กองสืบสวนที่หนึ่งกรมตำรวจ คัน ฮิโรกิ
            นี่คือบันทึกความทรงจำของการลงทัณฑ์
            เหล่าคนชั่วร้าย ด้วยน้ำมือของ
            เจ้าหน้าที่ตำรวจชั้นนำสายอาชีพ
        </details>
        <price>฿139.50</price>
        <quantity>125 เล่ม</quantity>
    </product>
    <product>
        <id>BK004</id>
        <name>I Reincarnated into an Otome Game as a Villainess With Only Destruction Flags</name>
        <details>ฉันพบว่าตัวเองมาเกิดใหม่เป็นคาตารีนา
            นางร้ายในเกมจีบหนุ่มที่เคยเล่นเมื่อชาติก่อน!?
            ซึ่งจุดจบมีแค่ 2 ทาง คือไม่ถูกเนรเทศก็ถูกฆ่าตาย!
            เกิดใหม่ปุ๊บก็เจอคำพยากรณ์สุดนรกแบบนี้ ไม่โหดร้ายเกินไปหน่อยเหรอ!?
            ต้องหาทางเลี่ยงจุดจบหายนะให้ได้!
            เรื่องราวเลิฟคอเมดี้แนวเลี่ยงจุดจบหายนะเปิดฉากแล้ว!!
        </details>
        <price>฿139.50</price>
        <quantity>155 เล่ม</quantity>
    </product>
    <product>
        <id>BK005</id>
        <name>The Fantasie of a Stepmother</name>
        <details>ถึงแม้ว่าทุกคนจะเปลี่ยนแปลงไปทีละนิด ฉันก็ยังโดดเดี่ยวจนถึงวินาทีสุดท้าย นั่นคือความคิดสุดท้ายของมาร์เซอเนสนอยวานรไดน์ 
        ก่อนที่เธอจะลืมตาตื่นขึ้นมาอีกครั้งในวันงานศพของสามีเมื่อ 7 ปีก่อน ท่ามกลางความสับสนงุนงง
        </details>
        <price>฿351.50</price>
        <quantity>200 เล่ม</quantity>
    </product>
</Bookshop>